name: Bug Report
description: Create a bug report to help us improve JEMs.
labels: [ "bug" ]
body:
    -   type: textarea
        attributes:
            label: Describe the Bug
            description: A clear and concise description of what the bug is
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduction Steps
            description: Tell us about the steps to reproduce the bug
            value: |
                1.
                2.
                3.
                ...
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Expected Result
            description: A clear and concise description of what you expected to happen
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Screenshots and Videos
            description: If applicable, add screenshots or videos to help explain your problem
        validations:
            required: false
    -   type: input
        attributes:
            label: Operating System
            description: The operating system you were using when the bug occured
            placeholder: Windows 11
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Mod Version
            description: The version of the mod you were using when the bug occured
            options:
                - "0.1.0"
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Minecraft Version
            description: The version of Minecraft you were using when the bug occured
            options:
                - "1.18.2"
                - "1.19.2"
        validations:
            required: true
    -   type: input
        attributes:
            label: Forge Version
            description: The version of Forge you were using when the bug occured
            placeholder: 40.2.0
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Other Mods
            description: Please list any other mods that were running when the crash happened
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Additional Context
            description: Add any extra context about the bug here
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "Thank you for taking the time to fill out this bug report and to help improve JEMs"
